name: Build and Deploy

on:
  push:
    branches:
      - main  # Change if your source branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use 18 to avoid react-scripts issues

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Deploy to deploy branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy         # Deployment branch
          folder: build          # React build output folder

